export const COMMENTS_READ_ALL_REQUEST = 'COMMENTS_READ_ALL_REQUEST';
export const COMMENTS_READ_ALL_SUCCESS = 'COMMENTS_READ_ALL_SUCCESS';
export const COMMENTS_READ_ALL_FAIL = 'COMMENTS_READ_ALL_FAIL';

export const COMMENT_PUT_REQUEST = 'COMMENT_PUT_REQUEST';
export const COMMENT_PUT_SUCCESS = 'COMMENT_PUT_SUCCESS';
export const COMMENT_PUT_FAIL = 'COMMENT_PUT_FAIL';