export const TEACHERS_LIST_REQUEST = 'TEACHERS_LIST_REQUEST';
export const TEACHERS_LIST_SUCCESS = 'TEACHERS_LIST_SUCCESS';
export const TEACHERS_LIST_FAIL = 'TEACHERS_LIST_FAIL';

export const TEACHER_DETAIL_REQUEST = 'TEACHER_DETAIL_REQUEST';
export const TEACHER_DETAIL_SUCCESS = 'TEACHER_DETAIL_SUCCESS';
export const TEACHER_DETAIL_FAIL = 'TEACHER_DETAIL_FAIL';

export const TEACHER_CREATE_REQUEST = 'TEACHER_CREATE_REQUEST';
export const TEACHER_CREATE_SUCCESS = 'TEACHER_CREATE_SUCCESS';
export const TEACHER_CREATE_FAIL = 'TEACHER_CREATE_FAIL';

export const TEACHER_UPDATE_REQUEST = 'TEACHER_UPDATE_REQUEST';
export const TEACHER_UPDATE_SUCCESS = 'TEACHER_UPDATE_SUCCESS';
export const TEACHER_UPDATE_FAIL = 'TEACHER_UPDATE_FAIL';

export const TEACHER_DETAIL_BYUSER_REQUEST = 'TEACHER_DETAIL_BYUSER_REQUEST';
export const TEACHER_DETAIL_BYUSER_SUCCESS = 'TEACHER_DETAIL_BYUSER_SUCCESS';
export const TEACHER_DETAIL_BYUSER_FAIL = 'TEACHER_DETAIL_BYUSER_FAIL';